openapi: 3.1.0
info:
  title: Google Calendar API
  description: Retrieve a list of events from a Google Calendar with a limit of 5 results.
  version: 1.0.0

servers:
  - url: https://www.googleapis.com/calendar/v3

paths:
  /calendars/{calendarId}/events:
    get:
      operationId: getCalendarEvents
      summary: Retrieve events from a Google Calendar
      description: Fetches details about events such as title, description, start and end times, location, and organizer.
      parameters:
        - name: calendarId
          in: path
          required: true
          description: The ID of the calendar (use 'primary' for the authenticated user's main calendar).
          schema:
            type: string
          example: primary
        - name: q
          in: query
          description: Search for events with a specific keyword.
          required: false
          schema:
            type: string
          example: "Meeting"
        - name: timeMin
          in: query
          description: Lower bound for event start time (RFC3339 timestamp).
          required: false
          schema:
            type: string
            format: date-time
          example: "2025-03-01T00:00:00Z"
        - name: timeMax
          in: query
          description: Upper bound for event start time (RFC3339 timestamp).
          required: false
          schema:
            type: string
            format: date-time
          example: "2025-03-10T23:59:59Z"
        - name: maxResults
          in: query
          description: Maximum number of events to return (Limited to 5 to prevent errors).
          required: true
          schema:
            type: integer
            default: 5
            enum: [5]  # Forces result count to be exactly 5
          example: 5
        - name: singleEvents
          in: query
          description: Expand recurring events into single events (Required for `orderBy=startTime`).
          required: false
          schema:
            type: boolean
            default: true
          example: true
        - name: orderBy
          in: query
          description: Order results by start time (Only works if `singleEvents=true`).
          required: false
          schema:
            type: string
            enum: [startTime]
          example: startTime
      responses:
        '200':
          description: A successful response containing event data (limited to 5 results).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventList'
        '400':
          description: Bad request, e.g., invalid parameters provided.
        '401':
          description: Unauthorized - Invalid or expired token.
        '403':
          description: Forbidden - User does not have access to the calendar.
        '404':
          description: Calendar not found.
        '500':
          description: Server error.

components:
  securitySchemes:
    google_oauth:
      type: oauth2
      description: Google OAuth2 authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            https://www.googleapis.com/auth/calendar.readonly: Read-only access to Google Calendar events

  schemas:
    EventList:
      type: object
      properties:
        kind:
          type: string
          description: The type of resource returned.
          example: "calendar#events"
        items:
          type: array
          maxItems: 5
          description: A list of events (maximum 5 results).
          items:
            $ref: '#/components/schemas/Event'

    Event:
      type: object
      properties:
        id:
          type: string
          description: Unique event identifier.
          example: "abc123"
        summary:
          type: string
          description: Event title.
          example: "Project Meeting"
        description:
          type: string
          description: Event details.
          example: "Discuss project roadmap and blockers."
        location:
          type: string
          description: Event location.
          example: "Microsoft Teams Meeting"
        start:
          type: object
          properties:
            dateTime:
              type: string
              format: date-time
              description: Start time of the event.
              example: "2025-03-04T10:00:00Z"
        end:
          type: object
          properties:
            dateTime:
              type: string
              format: date-time
              description: End time of the event.
              example: "2025-03-04T11:00:00Z"
        organizer:
          type: object
          properties:
            email:
              type: string
              description: Organizer's email address.
              example: "organizer@example.com"

security:
  - google_oauth: []
